name: umivar
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - scipy=1.9.3
  - samtools
  - pybedtools=0.9.0
  - pysam=0.20.0
  - numpy=1.23.5
  - networkx=2.8.8
  - pandas=1.5.2
  - bioconductor-survcomp
  - r-base=4.1.0
  - r-argparse
  - r-bbmle
  - r-data.table
  - r-ggplot2
  - r-gridextra
  - r-seqinr
  - r-vgam
  - r-scales
  - r-crayon
  - r-pkgconfig